apiVersion: v1
kind: Service
metadata:
  name: demo-web-app
  namespace: sample-app
  labels:
    app.kubernetes.io/name: demo-web-app
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name:  demo-web-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
