apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: staged-rollout-app-placement
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      name: staged-rollout-demo
      version: v1
  policy:
    placementType: PickAll
  strategy:
    type: External