apiVersion: placement.kubernetes-fleet.io/v1
kind: ClusterResourcePlacement
metadata:
  name: sample-app-placement
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      name: sample-app
      version: v1
  policy:
    placementType: PickAll
  strategy:
    type: External